# Generated by Django 2.1.4 on 2019-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('slot_time', models.DateTimeField()),
                ('open_seats', models.IntegerField()),
                ('taken_seats', models.IntegerField()),
                ('is_full', models.BooleanField(default=False)),
            ],
        ),
    ]
