# Generated by Django 2.1.4 on 2019-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='open_seats',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='check',
            name='taken_seats',
            field=models.IntegerField(default=-1),
        ),
    ]
