# Generated by Django 2.1.4 on 2019-03-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20190325_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='venue',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
